version: "3.9"
services:
  web:
    build: .

    ports:
      - "8000:8080"

    entrypoint: "/bin/bash -c /application/getmybeats/dev/start_dev_servers.sh"

    image: gmb-dev:Dockerfile

    volumes:
      - ./:/application/getmybeats


