version: "3.9"
services:
  web:
    build: .

    ports:
      - "8000:8080"

    environment:
      - DJANGO_SECRET_KEY=noodles  # arbitrary, throwaway value
      - 'DATABASE_SETTINGS={"DBHOST": "getmybeats.cdpivaepyp3k.us-west-2.rds.amazonaws.com", "DBNAME": "getmybeats", "DBPASSWORD": "Thatwasengl1sh!", "DBUSER": "root", "DBPORT": 3306}'

    entrypoint: "/bin/bash -c /application/getmybeats/dev/start_dev_servers.sh"

    image: gmb-dev:Dockerfile

    volumes:
      - ./:/application/getmybeats


