services:
  redis:
    command: redis-server
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_SETTINGS=${REDIS_SETTINGS}
      - DIGITALOCEAN_SETTINGS=${DIGITALOCEAN_SETTINGS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CODE_BRANCH=${CODE_BRANCH}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_SETTINGS=${DATABASE_SETTINGS}
      - S3_RELEASE_PROVISIONING_BUCKET=${S3_RELEASE_PROVISIONING_BUCKET}
      - S3_RELEASE_PROVISIONING_SCRIPT_NAME=${S3_RELEASE_PROVISIONING_SCRIPT_NAME}
      - S3_AUDIO_BUCKET=${S3_AUDIO_BUCKET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
