services:
  frontend:
    build:
        dockerfile: Dockerfile.frontend
        context: .
    volumes:
      - ../:/application/getmybeats
    command: bash -c "
      cd /application/getmybeats/frontend-v3/src &&
      npm install -g @angular/cli && npm install --package-lock-only &&
      npm install --save-dev @angular-devkit/build-angular@17.3.3 &&
      ng build --verbose"
  api-web:
    build:
      dockerfile: Dockerfile.backend
      context: .
    ports:
      - 80:80
    command: /bin/bash -c "
      cd /application/media && aws s3 sync s3://getmybeats-audio ./ &&
      cd /application/getmybeats &&
      . /opt/venvs/getmybeats/bin/activate &&
      ./manage.py migrate GetMyBeatsApp &&
      ./manage.py collectstatic --no-input &&
      echo 'starting gunicorn' && 
      /opt/venvs/getmybeats/bin/gunicorn -c GetMyBeatsApp/digitalocean/gunicorn/gunicorn_config.py GetMyBeatsSettings.wsgi --daemon &&
      echo 'echo starting nginx' && sudo systemctl restart nginx &&
      tail -f /var/log/nginx/access.log"
    volumes:
      - ../:/application/getmybeats
      - ./GetMyBeatsApp/digitalocean/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/environment:/etc/environment
    depends_on:
      frontend:
        condition: service_completed_successfully
