FROM ubuntu:22.04

RUN apt update

RUN apt install -y sudo curl iputils-ping nginx redis-tools python3 python3-pip mysql-client net-tools

RUN mkdir -p /application/getmybeats

COPY ./ /application/getmybeats

RUN cd /application/getmybeats && . venv/bin/activate && pip3 install -r requirements.txt
