FROM ubuntu:22.04


ARG application_directory="/application/getmybeats"
ARG venv_directory="/opt/venvs/getmybeats"


# first things first
RUN apt update
RUN apt install -y sudo curl iputils-ping nginx redis-tools \
    python3 python3-pip mysql-client net-tools python3.10-venv npm unzip systemctl


# set up directories
RUN mkdir -p "$application_directory"
RUN mkdir -p /var/log/django/
RUN mkdir -p /var/log/gunicorn/
RUN mkdir -p /application/media
RUN mkdir -p "$venv_directory"
RUN mkdir -p /root/.aws


# set up core files
RUN touch /var/log/gunicorn/error.log
RUN touch /var/log/django/general.log
RUN python3 -m venv "$venv_directory"
COPY ./ "$application_directory"


# install and use node 18
# build and ship frontend
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
RUN . ~/.bashrc && nvm install 18 && cd "$application_directory"/frontend && npm install && npm run build


# configure awscli auth
RUN cp "$application_directory"/dev/.aws/credentials /root/.aws
RUN cp "$application_directory"/dev/.aws/config /root/.aws

RUN cd "$application_directory" && . /opt/venvs/getmybeats/bin/activate && pip3 install -r requirements.txt
