FROM --platform=linux/amd64 node:22.3.0


ARG application_directory="/application/getmybeats"


# first things first
RUN apt update
RUN apt install -y sudo curl iputils-ping python3 python3-pip net-tools npm unzip systemctl vim


# set up directories
RUN mkdir -p "$application_directory"
RUN mkdir -p /root/.aws


# set up core files
COPY ./ "$application_directory"


# configure awscli auth
RUN cp "$application_directory"/dev/.aws/credentials /root/.aws
RUN cp "$application_directory"/dev/.aws/config /root/.aws


# install awscli
RUN cd && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN cd && unzip awscliv2.zip
RUN cd && sudo ./aws/install


# install media files into assets dir
RUN cd && aws s3 sync s3://getmybeats-audio-dev "$application_directory"/frontend-v3/src/assets/
