FROM ubuntu:22.04


ARG application_directory="/application/getmybeats"
ARG venv_directory="/opt/venvs/getmybeats"

RUN apt update

RUN apt install -y sudo curl iputils-ping nginx redis-tools python3 python3-pip mysql-client net-tools python3.10-venv

# set up directories
RUN mkdir -p "$application_directory"
RUN mkdir -p /var/log/django/
RUN mkdir -p /var/log/gunicorn/
RUN mkdir -p /application/media
RUN mkdir -p "$venv_directory"

# set up core files
RUN touch /var/log/gunicorn/error.log
RUN touch /var/log/django/general.log
RUN python3 -m venv "$venv_directory"/venv

COPY ./ "$application_directory"

RUN cd "$application_directory" && . /opt/venvs/getmybeats/venv && pip3 install -r requirements.txt
