# Generated by Django 4.1.4 on 2023-02-19 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_bytes', models.BinaryField(max_length=1000)),
                ('file_upload', models.FileField(upload_to='')),
                ('fk_uploaded_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio',
                'managed': True,
            },
        ),
    ]
