# Generated by Django 4.1.4 on 2023-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0002_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='status',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
