# Generated by Django 4.1.4 on 2024-02-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0004_remove_audio_raw_bytes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='file_upload',
            new_name='audio_file_upload',
        ),
        migrations.AddField(
            model_name='audio',
            name='image_file_upload',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='s3_artwork_upload_path',
            field=models.CharField(max_length=200, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='s3_audio_upload_path',
            field=models.CharField(max_length=200, null=True)
        ),
    ]
