# Generated by Django 4.2.10 on 2024-03-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0004_remove_audio_raw_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('environment', models.JSONField()),
            ],
            options={
                'db_table': 'production_release',
                'managed': True,
            },
        ),
    ]
