# Generated by Django 4.1.4 on 2024-01-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0004_remove_audio_raw_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='s3_audio_upload_path',
            field=models.CharField(max_length=200, null=True)
        ),
        migrations.AddField(
            model_name='audio',
            name='s3_artwork_upload_path',
            field=models.CharField(max_length=200, null=True)
        ),
    ]
