# Generated by Django 4.1.4 on 2024-01-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0006_auto_20240125_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='s3_audio_upload_path',
            field=models.CharField(max_length=200, unique=True)
        ),
    ]
