# Generated by Django 4.1.4 on 2024-02-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0006_audio__populate_s3_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='s3_artwork_upload_path',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='s3_audio_upload_path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
