# Generated by Django 4.2.10 on 2024-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0006_renewedsslconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('params', models.CharField(max_length=100)),
                ('headers', models.JSONField()),
                ('body', models.JSONField()),
                ('user_agent', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'site_visit_request',
                'managed': True,
            },
        ),
    ]
