# Generated by Django 4.2.10 on 2024-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0007_sitevisitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitrequest',
            name='user_agent',
            field=models.CharField(max_length=200),
        ),
    ]
