# Generated by Django 4.2.10 on 2024-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0008_alter_sitevisitrequest_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='length',
        ),
        migrations.AddField(
            model_name='audio',
            name='filename_hash',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
