# Generated by Django 4.2.10 on 2024-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0009_remove_audio_length_audio_filename_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='filename_hash_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
