# Generated by Django 4.2.10 on 2024-07-03 05:45

import GetMyBeatsApp.helpers.db_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0010_audio_filename_hash_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='status',
        ),
        migrations.AddField(
            model_name='audio',
            name='s3_upload_path',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_upload',
            field=models.FileField(upload_to=GetMyBeatsApp.helpers.db_utilities.get_file_upload_path_pre_save),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
