# Generated by Django 4.2.10 on 2024-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0010_audio_filename_hash_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='file_upload',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='status',
        ),
        migrations.AddField(
            model_name='audio',
            name='ext',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='audio',
            name='s3_upload_path',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
