# Generated by Django 4.2.10 on 2024-10-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0012_userexperiencereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFetchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_uuid', models.UUIDField()),
            ],
            options={
                'db_table': 'audio_fetch_request',
                'managed': True,
            },
        ),
    ]
