# Generated by Django 4.2.10 on 2024-12-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0013_audiofetchrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioArtwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('filename_hash', models.CharField(blank=True, max_length=300, null=True)),
                ('filename_hash_updated_at', models.DateTimeField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('s3_upload_path', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('ext', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'audio_artwork',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GetMyBeatsApp.audioartwork'),
        ),
    ]
