# Generated by Django 4.2.10 on 2025-08-02 18:51

import GetMyBeatsApp.helpers.db_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0014_audioartwork_audio_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitrequest',
            name='user_agent',
            field=models.CharField(max_length=512),
        ),
    ]
