# Generated by Django 4.2.10 on 2025-09-22 04:40

import GetMyBeatsApp.helpers.db_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0015_sitevisitrequest_user_agent_512_chars'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')])),
                ('message', models.CharField(max_length=1024)),
                ('api_module', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'log_entry',
                'managed': True,
            },
        )
    ]
