# Generated by Django 4.2.10 on 2026-03-24 05:15

import GetMyBeatsApp.helpers.db_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0016_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.CharField(blank=True, default='micah', max_length=200),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to=GetMyBeatsApp.helpers.db_utilities.lowercase_filename),
        ),
        migrations.AlterField(
            model_name='audioartwork',
            name='file',
            field=models.FileField(upload_to=GetMyBeatsApp.helpers.db_utilities.lowercase_filename),
        ),
    ]
