name: Getmybeats CICD

on:
  push:
    branches: [ "*" ]

jobs:
  test-api:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.12.7]

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          cd /application/getmybeats
          . /opt/venvs/getmybeats/bin/activate
          ./manage.py test
