name: Django CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          cd
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          cd /application/getmybeats/ci && docker compose -f docker-compose.ci.yml run --rm --name ci api-ci
